export const FEATURE_SECTIONS = {
  GLOBAL: 'global',
  DECK_VIEW: 'deck-view',
  DECK_BUILDER: 'deck-builder',
  SEARCH_RESULTS: 'search-results'
}

export const BUS_EVENTS = {
  ADD_CARD_TO_DECK: 'ADD_CARD_TO_DECK',
  CALLED_DESTROYENTRY: 'CALLED_DESTROYENTRY',
  CALLED_ADDCARD: 'CALLED_ADDCARD',
  CALLED_CLEANUP: 'CALLED_CLEANUP',
  CALLED_UPDATEENTRY: 'CALLED_UPDATEENTRY',
  CALLED_REPLACEENTRY: 'CALLED_REPLACEENTRY',
  CALLED_CREATEENTRY: 'CALLED_CREATEENTRY',
  CLEAN_UP_DECK: 'CLEAN_UP_DECK',
  MODIFY_CLEAN_UP: 'MODIFY_CLEAN_UP',
  REMOVE_CARD_FROM_DECK: 'REMOVE_CARD_FROM_DECK',
  REQUEST_DECK: 'REQUEST_DECK',
  REQUEST_EDHREC_RECOMENDATIONS: 'REQUEST_EDHREC_RECOMENDATIONS',
  SCRYFALL_LISTENERS_READY: 'SCRYFALL_LISTENERS_READY',
  SCRYFALL_PUSH_NOTIFICATION: 'SCRYFALL_PUSH_NOTIFICATION',
  TAGGER_READY: 'TAGGER_READY',
  TAGGER_TAGS_REQUEST: 'TAGGER_TAGS_REQUEST'
}
